name: big-o-primer-notebook
channels:
  - conda-forge
  - default
dependencies:
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - jupyter
  - ipython
  - python
  - numpy
  - pip
  - future
  - pandas
  - ipywidgets
  - seaborn
  - voila
